on:
  release:
    types:
      - published

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "${{ github.event.release }}"
          echo "${{ github.event_name }}"
          echo "${{ github.event.release.prerelease }}"
      - name: Only release
        if: github.event_name == 'release' && github.event.release.prerelease == false
        run: |
          echo "published!"
